### ISSUE TITLE
Column id not found

### ISSUE THREAD

**Issue by dvohra** [keedio/flume-ng-sql-source#18]
Column 'id' is in the MySQL table, but getting following exception:

2015-09-12 09:43:37,496 (PollableSourceRunner-SQLSource-mySQLsource) [INFO - org.apache.flume.source.SQLSource.process(SQLSource.java:100)] Query: SELECT null FROM wlslog WHERE id>-1 ORDER BY id;
2015-09-12 09:43:37,541 (PollableSourceRunner-SQLSource-mySQLsource) [ERROR - org.apache.flume.source.SQLSource.process(SQLSource.java:157)] SQL exception, check if query for source mySQLsource is correctly constructed
java.sql.SQLException: Column 'id' not found.
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1094)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:997)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:983)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:928)
	at com.mysql.jdbc.ResultSetImpl.findColumn(ResultSetImpl.java:1162)
	at com.mysql.jdbc.ResultSetImpl.getString(ResultSetImpl.java:5728)
	at org.apache.flume.source.SQLSource.process(SQLSource.java:133)
	at 

The issue is fixed and may be closed. The issue was due to the wrong source name in a configuration setting.

agent.sources = mySQLsource
agent.sources.sql-source.columns.to.select =*

**Comment by lucarosellini** [comment]
Issue closed since it was due to a configuration error, not to a bug in the code.
