### ISSUE TITLE
Can't get data from Mysql

### ISSUE THREAD

**Issue by GeorgeGuoCN** [keedio/flume-ng-sql-source#34]
When I get data from Mysql, the Custom query:
agent.sources.sqlSource.start.from = 20170801000000
agent.sources.sqlSource.custom.query = SELECT * FROM order WHERE PAY_TIME > $@$ ORDER BY PAY_TIME ASC

Error log:
2017-08-01 19:16:56,435 (PollableSourceRunner-SQLSource-sqlSource) [WARN - org.hibernate.engine.jdbc.spi.SqlExceptionHelper$StandardWarningHandler.logWarning(SqlExceptionHelper.java:233)] Incorrect datetime value: '6939' for column 'PAY_TIME' at row 1
Exception in thread "PollableSourceRunner-SQLSource-sqlSource" java.lang.AbstractMethodError: org.keedio.flume.source.SQLSource.getMaxBackOffSleepInterval(),

software version:
 Mysql:5.6.16
JDK:1.8
flume:1.7.0

**Comment by lufeng1102** [comment]
It seems like a data type issue from 'PAY_TIME‘ field.

**Comment by mvalleavila** [comment]
Hello,

As lufen commented it seem that the error is related with data types.

The value of PAY_TIME isn't a valid datetime, and the comparison with 20170801000000 can't be done. (Incorrect datetime value: '6939')

Maybe PAY_TIME column is an int or double (a time period?)

**Comment by skt0001** [comment]
Hi,
I am getting an error while reading logs from rabbitmq to HDFS path using Flume.

Please can somebody help me to rectify the issue.

Exception in thread "PollableSourceRunner-RabbitMQSource-rabbitmq-source1" java.lang.AbstractMethodError: org.apache.flume.source.rabbitmq.RabbitMQSource.getBackOffSleepIncrement()J
	at org.apache.flume.source.PollableSourceRunner$PollingRunner.run(PollableSourceRunner.java:142)
	at java.lang.Thread.run(Thread.java:748)
