### ISSUE TITLE
AbstractMethodError？

### ISSUE THREAD

**Issue by AomoDa** [keedio/flume-ng-sql-source#35]
2017-08-23 23:16:15,324 (lifecycleSupervisor-1-4) [INFO - org.apache.flume.instrumentation.MonitoredCounterGroup.start(MonitoredCounterGroup.java:95)] Component type: SOURCE, name: SOURCESQL.r1 started
2017-08-23 23:16:15,324 (lifecycleSupervisor-1-2) [INFO - org.apache.flume.instrumentation.MonitoredCounterGroup.register(MonitoredCounterGroup.java:119)] Monitored counter group for type: SINK, name: h1: Successfully registered new MBean.
2017-08-23 23:16:15,325 (lifecycleSupervisor-1-2) [INFO - org.apache.flume.instrumentation.MonitoredCounterGroup.start(MonitoredCounterGroup.java:95)] Component type: SINK, name: h1 started
Exception in thread "PollableSourceRunner-SQLSource-r1" java.lang.AbstractMethodError: org.keedio.flume.source.SQLSource.getMaxBackOffSleepInterval()J
	at org.apache.flume.source.PollableSourceRunner$PollingRunner.run(PollableSourceRunner.java:150)
	at java.lang.Thread.run(Thread.java:748)
2017-08-23 23:16:37,344 (SinkRunner-PollingRunner-DefaultSinkProcessor) [INFO - org.apache.flume.sink.hdfs.HDFSCompressedDataStream.configure(HDFSCompressedDataStream.java:64)] Serializer = TEXT, UseRawLocalFileSystem = false
2017-08-23 23:16:37,354 (SinkRunner-PollingRunner-DefaultSinkProcessor) [INFO - org.apache.flume.sink.hdfs.BucketWriter.open(BucketWriter.java:251)] Creating hdfs://10.105.236.14:8020/user/flume/mysql/userinfo/userinfo/dt=2017-08-23/FlumeData.1503501397345.snappy.tmp
2017-08-23 23:16:38,340 (hdfs-h1-call-runner-0) [INFO - org.apache.hadoop.io.compress.CodecPool.getCompressor(CodecPool.java:153)] Got brand-new compressor [.snappy]
Exception in thread "PollableSourceRunner-SQLSource-r2" java.lang.AbstractMethodError: org.keedio.flume.source.SQLSource.getMaxBackOffSleepInterval()J
	at org.apache.flume.source.PollableSourceRunner$PollingRunner.run(PollableSourceRunner.java:150)
	at java.lang.Thread.run(Thread.java:748)

**Comment by mvalleavila** [comment]
Hello,

Can you share more info about the error?
Configuration, the complete stack trace, the scenario where the issue happened...

Regards

**Comment by lazaromedina** [comment]
Since Apache-Flume 1.7.0, PollableSource implements new methods for managing backoff times. 
Release flume-sql-source 1.5.0 is compatible with upper versions Apache flume since 1.7.0. 
https://issues.apache.org/jira/browse/FLUME-2729
Thanks
