### ISSUE TITLE
it is necesary to delete directory of logs at first launch

### ISSUE THREAD

**Issue by lazaromedina** [keedio/flume-ng-sql-source#4]
ftpsourceutils always asummes it does not exists /var/lib/flume.

**Comment by dvohra** [comment]
The other post may be deleted.

As suggested, deleted the /var/lib/flume directory and got the following error:

15/01/24 15:48:54 ERROR source.SQLSourceUtils: Error reading incremental value from status file!!!
java.io.FileNotFoundException: /var/lib/flume/sql-source.status (No such file or directory)
at java.io.FileInputStream.open(Native Method)
at java.io.FileInputStream.(FileInputStream.java:146)
at java.io.FileReader.(FileReader.java:72)
at org.apache.flume.source.SQLSourceUtils.getStatusFileIncrement(SQLSourceUtils.java:95)
at org.apache.flume.source.SQLSource.process(SQLSource.java:96)
at org.apache.flume.source.PollableSourceRunner$PollingRunner.run(PollableSourceRunner.java:139)
at java.lang.Thread.run(Thread.java:745)
15/01/24 15:48:54 INFO source.SQLSource: Query: SELECT * FROM WLSLOG WHERE id>-1 ORDER BY id;
15/01/24 15:48:54 ERROR source.SQLSource: SQL exception, check if query for source sql-source is correctly constructed
java.sql.SQLSyntaxErrorException: ORA-00911: invalid character

at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:450)
at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:399)
at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1059)
at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:522)
at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:257)
at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:587)
at oracle.jdbc.driver.T4CStatement.doOall8(T4CStatement.java:210)
at oracle.jdbc.driver.T4CStatement.doOall8(T4CStatement.java:30)

**Comment by dvohra** [comment]
It is not necessary to delete log directory /var/lib/flume. With MySQL SQL Source if the /var/lib/flume directory is created the Flume agent runs without error.
