### ISSUE TITLE
[ERROR - org.keedio.flume.source.SQLSourceHelper.checkJsonValues(SQLSourceHelper.java:280)] Query value in status file doesn't match with configured in properties file

### ISSUE THREAD

**Issue by starbow727** [keedio/flume-ng-sql-source#41]
2017-09-05 15:59:20,960 (conf-file-poller-0) [ERROR - org.keedio.flume.source.SQLSourceHelper.checkJsonValues(SQLSourceHelper.java:280)] Query value in status file doesn't match with configured in properties file
2017-09-05 15:59:20,961 (conf-file-poller-0) [ERROR - org.keedio.flume.source.SQLSourceHelper.getStatusFileIndex(SQLSourceHelper.java:232)] Exception reading status file, doing back up and creating new status file
Unexpected exception at position -1: null
        at org.keedio.flume.source.SQLSourceHelper.checkJsonValues(SQLSourceHelper.java:281)
        at org.keedio.flume.source.SQLSourceHelper.getStatusFileIndex(SQLSourceHelper.java:228)
        at org.keedio.flume.source.SQLSourceHelper.<init>(SQLSourceHelper.java:113)
        at org.keedio.flume.source.SQLSource.configure(SQLSource.java:66)
        at org.apache.flume.conf.Configurables.configure(Configurables.java:41)
        at org.apache.flume.node.AbstractConfigurationProvider.loadSources(AbstractConfigurationProvider.java:326)
        at org.apache.flume.node.AbstractConfigurationProvider.getConfiguration(AbstractConfigurationProvider.java:97)
        at org.apache.flume.node.PollingPropertiesFileConfigurationProvider$FileWatcherRunnable.run(PollingPropertiesFileConfigurationProvider.java:140)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
2017-09-05 15:59:21,133 (conf-file-poller-0) [INFO - org.hibernate.annotations.common.reflection.java.JavaReflectionManager.<clinit>(JavaReflectionManager.java:66)] HCANN000001: Hibernate Commons Annotations {4.0.5.Final}

**Comment by mvalleavila** [comment]
Hello,
The message "Query value in status file doesn't match with configured in properties file" means that the query has been change in the properties file after a previous execution.

The old query has been saved in status file and doesn't match with the new one. So a new status file is created, doing a backup of the previous ("doing back up and creating new status file")

Regards

**Comment by starbow727** [comment]
I see. Thank you
