### ISSUE TITLE
Exception in thread "PollableSourceRunner-SQLSource-s1" java.lang.AbstractMethodError: org.keedio.flume.source.SQLSource.getMaxBackOffSleepInterval()J

### ISSUE THREAD

**Issue by starbow727** [keedio/flume-ng-sql-source#42]
t for file: /root/.flume/file-channel/data/log-1 position: 204899035 logWriteOrderID: 1504748885512
Exception in thread "PollableSourceRunner-SQLSource-s1" java.lang.AbstractMethodError: org.keedio.flume.source.SQLSource.getMaxBackOffSleepInterval()J
        at org.apache.flume.source.PollableSourceRunner$PollingRunner.run(PollableSourceRunner.java:154)
        at java.lang.Thread.run(Thread.java:745)
2017-09-07 09:52:28,141 (Log-BackgroundWorker-c1) [INFO - org.apache.flume.channel.file.EventQueueBackingStoreFile.beginCheckpoint(EventQueueBackingStoreFile.java:230)] Start checkpoint for /root/.flume/file-channel/checkpoint/checkpoint, elements to sync = 12300
2017-09-07 09:52:28,216 (Log-BackgroundWorker-c1) [INFO - org.apache.flume.channel.file.EventQueueBackingStoreFile.checkpoint(EventQueueBackingStoreFile.java:255)] Updating checkpoint metadata: logWriteOrderID: 1504748897975, queueSize: 999962, queueHead: 157908
2017-09-07 09:52:28,297 (Log-BackgroundWorker-c1) [INFO - org.apache.flume.channel.file.Log.writeCheckpoint(Log.java:1034)] Updated checkpoint for file: /root/.flume/file-channel/data/log-1 position: 210597771 logWriteOrderID: 1504748897975

**Comment by mvalleavila** [comment]
Hello,

The stack trace is pasted partially, with this info I can't help you.
Anyway it seems to be an error in the Flume Channel. You can try to search in the web some info about these error

Regards
